### ISSUE TITLE
data_download.sh Hanging with no HTTP response returned

### ISSUE THREAD

**Issue by derhornspieler** [philipperemy/deep-learning-bitcoin#12]
./data_download.sh
--2017-12-14 21:42:18--  http://api.bitcoincharts.com/v1/csv/coinbaseUSD.csv.gz
Resolving api.bitcoincharts.com... 144.76.195.253
Connecting to api.bitcoincharts.com|144.76.195.253|:80... connected.
HTTP request sent, awaiting response... 

***TESTED in browser, same hang up.

**Comment by philipperemy** [comment]
It's a big file. So maybe you're good to use a tool that can resume downloads.

You can try "Free Download Manager" or the Mozilla extension DownThemAll. :)

**Comment by derhornspieler** [comment]
The website does not respond either when using the URL directly in a browser.

I will try again. Thanks for response. :-)

Sent from my iPhone

On Dec 15, 2017, at 07:21, Philippe Rémy <notifications@github.com<mailto:notifications@github.com>> wrote:


It's a big file. So maybe you're good to use a tool that can resume downloads.

You can try "Free Download Manager" or the Mozilla extension DownThemAll. :)

**Comment by philipperemy** [comment]
I tried it now and it works. So maybe download it from another place :)

**Comment by derhornspieler** [comment]
Yer right mate.  Just tried it this morning and its working beautifully.  Interested to see the results from latest BTC pulls.

Thank god for DO VPS’s. Ha ha.

**Comment by philipperemy** [comment]
Awesome @derhornspieler ! Great news :)
