### ISSUE TITLE
no code from building model?

### ISSUE THREAD

**Issue by scotthuang1989** [philipperemy/deep-learning-bitcoin#14]
Hi guys,

I take a look at the code, I think all of the code are about downloading and pre-processing data. no training/model code?

**Comment by philipperemy** [comment]
Training is done on NVIDIA DIGITS

https://github.com/nvidia/digits

**Comment by scotthuang1989** [comment]
thanks.  I am not familiar with this tool, I will take a look...

**Comment by philipperemy** [comment]
@scotthuang1989 thank you
