### ISSUE TITLE
pandas.core.config.OptionError: "No such keys(s): 'display.height'"

### ISSUE THREAD

**Issue by dedetuga** [philipperemy/deep-learning-bitcoin#18]
Hi I'm getting this error pandas.core.config.OptionError: "No such keys(s): 'display.height'"
after run coinbaseUSD.csv 1 

i think is something  relative with pandas, what is the vertion you atre using?

`$ python3 data_generator.py /tmp/btc-trading-patterns/ /tmp/coinbaseUSD.csv 1 

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "data_generator.py", line 15, in <module>
    pd.set_option('display.height', 1000)
  File "/home/filipe/.local/lib/python3.5/site-packages/pandas/core/config.py", line 227, in __call__
    return self.__func__(*args, **kwds)
  File "/home/filipe/.local/lib/python3.5/site-packages/pandas/core/config.py", line 119, in _set_option
    key = _get_single_key(k, silent)
  File "/home/filipe/.local/lib/python3.5/site-packages/pandas/core/config.py", line 83, in _get_single_key
    raise OptionError('No such keys(s): {pat!r}'.format(pat=pat))
pandas.core.config.OptionError: "No such keys(s): 'display.height'"
`

**Comment by philipperemy** [comment]
Thanks for reporting.

Fixed in https://github.com/philipperemy/deep-learning-bitcoin/commit/b04f115743915b74a0f77ee38f5f47bf8c1200c4

**Comment by dedetuga** [comment]
thanks

**Comment by devuc** [comment]
please help me i am having pandas._config.config.OptionError: "No such keys(s): 'io.excel.zip.reader'"
