### ISSUE TITLE
Getting per minute prices of bitcoin from the dataset

### ISSUE THREAD

**Issue by samre12** [philipperemy/deep-learning-bitcoin#7]
My objective is to extract per minute prices of bitcoin from the history of transactions. Can you point in me in the direction of extracting of the prices using your code? 
Any help would be really appreciated.

**Comment by tahmi123** [comment]
import datetime

import pandas as pd




def file_processor(data_file):
    print('Reading bitcoin market data file here: {}.'.format(data_file))
    d = pd.read_table(data_file, sep=',', header=None, index_col=0, names=['price', 'volume'])
    d.index = d.index.map(lambda ts: datetime.datetime.fromtimestamp(int(ts)))
    d.index.names = ['DateTime_UTC']
    p = pd.DataFrame(d['price'].resample('5Min').ohlc())
    p.columns = ['price_open', 'price_high', 'price_low', 'price_close']
    v = pd.DataFrame(d['volume'].resample('5Min').sum())
    v.columns = ['volume']
    p['volume'] = v['volume']

    # drop NaN values.
    # for example sometimes we don't have data for like one hour in a row.
    # So we have NaN buckets of 5Min in this particular hour.
    # Our convention is to avoid those NaN values and drop them!
    p = p.dropna()
    p.to_csv('/tmp/bitcoin_coinbase_M5.csv', sep='\t')
    return p

the above code shows the data_manager script edit theses lines "v = pd.DataFrame(d['volume'].resample('5Min').sum())" and "p = pd.DataFrame(d['price'].resample('5Min').ohlc())" to "v = pd.DataFrame(d['volume'].resample('1Min').sum())" and "p = pd.DataFrame(d['price'].resample('1Min').ohlc())"

**Comment by samre12** [comment]
@tahmi123 thanks for the update! I just need to confirm that if I don't drop the NaN values, then would the dataset generated comprise of Bitcoin prices for each minute from a specified time point (though many values will be NaN due to absence of transaction history)?
My use case requires me to deal with consecutive per minute price of Bitcoin without any gaps so just dropping Nans would not serve the purpose.

**Comment by philipperemy** [comment]
@samre12 yes you will have all the correct timestamps but lots of NaN. If you don't want to drop them and for some particular problems I fully understand, you can call `.fillna(0)` and all the NaN will be converted to 0.

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.fillna.html

**Comment by samre12** [comment]
@philipperemy thanks for the clarification. 👍
