### ISSUE TITLE
Docker image for the repo 

### ISSUE THREAD

**Issue by moiseevigor** [philipperemy/deep-learning-bitcoin#8]
I'm using the code inside the docker image and it works smoothly, do you consider a pull request with the build script?

**Comment by philipperemy** [comment]
Sure can you provide it?

**Comment by philipperemy** [comment]
Also thank you for the good news! Happy that it's working smoothly :)

**Comment by moiseevigor** [comment]
Done, please check and let me know. Looking forward to contribute more!

**Comment by philipperemy** [comment]
Merged :)
